### ISSUE TITLE
generic-arm64 only builds an uncompressed image which is 5GB

### ISSUE THREAD

**Issue by terceiro** [m5p3nc3r/meta-ewaol-machine#11]
Hi,

I just built a bunch of machines here, and noticed that the generic-arm64 machine only builds an uncompressed root filesystem, which is 5GB. For local builds that's fine, but for CI environments that can get expensive quickly. Other machines (n2sdp, ava) produce a compressed image (`.wic.gz`), can we get that for generic-arm64 as well?

```
| Image--5.15.44+git0+947149960e_eb3df10e3f-r0-generic-arm64-20220630143628.bin   | 42M  |
| ewaol-baremetal-image-efi-disk.wks                                              | 473B |
| ewaol-baremetal-image-generic-arm64-20220701174054.rootfs.manifest              | 115K |
| ewaol-baremetal-image-generic-arm64-20220701174054.rootfs.wic                   | 5G   | *****
| ewaol-baremetal-image-generic-arm64-20220701174054.testdata.json                | 341K | 
| ewaol-baremetal-image.env                                                       | 5K   | 
| linuxaa64.efi.stub                                                              | 76K  | 
| modules--5.15.44+git0+947149960e_eb3df10e3f-r0-generic-arm64-20220630143628.tgz | 11M  | 
| systemd-bootaa64.efi                                                            | 112K | 
```

**Comment by petegriffin** [comment]
@terceiro you can make it generate a wic.gz by updating IMAGE_FSTYPES variable to include wic.gz. That variable is currently defined in meta-arm/conf/machine/generic-arm64.conf for generic-arm64.

However I think that is what this commit https://github.com/m5p3nc3r/meta-ewaol-machine/pull/9/commits/148d61951bf068a5be930562d4ed270ce349e700 is also trying to solve by introducing the ci-constraints.yml @benmordaunt please correct me if I'm wrong.

So it should generate a wic.gz by also including ci-constraints.yml on the kas build command

**Comment by benmordaunt** [comment]
Hi both,

Yes, `ci-constraints.yml` was introduced as a place to put "nice-to-haves" in a CI environment, such as a consistent image output and compression format. As long as the machine type defines a WKS (Kickstart) file to describe the partitioning information, you can specify one of the `wic.*` types in `IMAGE_FSTYPES`. That being said, I don't immediately see a suitable wks in `meta-arm/tree/master/meta-arm-bsp/wic`. Let me check this.

/ Ben

**Comment by terceiro** [comment]
Fair enough. In that case there is not really anything to be fixed here, so I'm closing this. Thanks for the info!
